// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFileExecutable(arg1:Array<string>):Promise<Array<string>>;

export function ListBundledRuntimes():Promise<Array<string>>;

export function ListLanguageAvailability(arg1:Array<string>):Promise<main.LanguageAvailability>;

export function RunFileExecutable(arg1:main.Data):Promise<main.Data>;
