// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFileExecutable(arg1:string):Promise<string>;

export function RunFileExecutable(arg1:main.Data):Promise<main.ResponseData>;
