name: Desktop App builds

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-desktop:
    name: Build ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
            artifact: app-desktop-linux
          - os: windows-latest
            platform: windows/amd64
            artifact: app-desktop-windows
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libjavascriptcoregtk-4.1-dev \
            libglib2.0-dev \
            libsoup-3.0-dev

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Install Wails CLI
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.1
          echo "$HOME/go/bin" >> "$GITHUB_PATH"

      - name: Build desktop app
        env:
          WAILS_SKIP_FRONTEND_INSTALL: "true"
        run: |
          rm -rf build/bin
          if [ "${{ runner.os }}" = "Linux" ]; then
            wails build -platform ${{ matrix.platform }} -tags webkit2_41
          else
            wails build -platform ${{ matrix.platform }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            build/bin/**
