name: Wails build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            {
              name: wailsGoCodeInteractiveApp,
              platform: linux/amd64,
              os: ubuntu-latest,
            },
            {
              name: wailsGoCodeInteractiveApp,
              platform: windows/amd64,
              os: windows-latest,
            },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v3
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          build-obfuscate: true
          go-version: 1.24
          node-version: 20.x
